export const translatedInfo: Record<string, Record<string, string>> = {
    "Language": {
        "de": "Deutsch",
        "en": "English",
        "pl": "Polski",
        "es": "Español",
        "fr": "Français",
        "it": "Italiano",
        "pt": "Português",
        "ru": "Русский",
        "tr": "Türkçe",
    },
    "EC Inventory Hub 2026 by R.Stolz": {
        "de": "EC Inventory Hub © 2026 von R.Stolz",
        "en": "EC Inventory Hub © 2026 by R.Stolz",
        "pl": "EC Inventory Hub © 2026 przez R.Stolz",
        "es": "EC Inventory Hub © 2026 por R.Stolz",
        "fr": "EC Inventory Hub © 2026 par R.Stolz",
        "it": "EC Inventory Hub © 2026 da R.Stolz",
        "pt": "EC Inventory Hub © 2026 por R.Stolz",
        "ru": "EC Inventory Hub © 2026 от R.Stolz",
        "tr": "EC Inventory Hub © 2026 tarafından R.Stolz",
    },
    "Profile GitHub": {
        "de": "GitHub Profil",
        "en": "GitHub Profile",
        "pl": "Profil GitHub",
        "es": "Perfil de GitHub",
        "fr": "Profil GitHub",
        "it": "Profilo GitHub",
        "pt": "Perfil do GitHub",
        "ru": "Профиль GitHub",
        "tr": "GitHub Profili",
    },
    "Username": {
        "de": "Benutzername",
        "en": "Username",
        "pl": "Nazwa użytkownika",
        "es": "Nombre de usuario",
        "fr": "Nom d'utilisateur",
        "it": "Nome utente",
        "pt": "Nome de usuário",
        "ru": "Имя пользователя",
        "tr": "Kullanıcı adı",
    },
    "Name": {
        "de": "Name",
        "en": "Name",
        "pl": "Imię",
        "es": "Nombre",
        "fr": "Nom",
        "it": "Nome",
        "pt": "Nome",
        "ru": "Имя",
        "tr": "İsim",
    },
    "Location": {
        "de": "Ort",
        "en": "Location",
        "pl": "Lokalizacja",
        "es": "Ubicación",
        "fr": "Emplacement",
        "it": "Posizione",
        "pt": "Localização",
        "ru": "Местоположение",
        "tr": "Konum",
    },
    "Followers": {
        "de": "Follower",
        "en": "Followers",
        "pl": "Obserwujący",
        "es": "Seguidores",
        "fr": "Abonnés",
        "it": "Follower",
        "pt": "Seguidores",
        "ru": "Подписчики",
        "tr": "Takipçiler",
    },
    "Following": {
        "de": "Folgt",
        "en": "Following",
        "pl": "Obserwuje",
        "es": "Siguiendo",
        "fr": "Abonnements",
        "it": "Seguiti",
        "pt": "Seguindo",
        "ru": "Подписки",
        "tr": "Takip Edilenler",
    },
    "Public Repositories": {
        "de": "Öffentliche Repositories",
        "en": "Public Repositories",
        "pl": "Publiczne repozytoria",
        "es": "Repositorios públicos",
        "fr": "Dépôts publics",
        "it": "Repository pubblici",
        "pt": "Repositórios públicos",
        "ru": "Публичные репозитории",
        "tr": "Halka Açık Depolar",
    },
    "Visit Profile": {
        "de": "Profil besuchen",
        "en": "Visit Profile",
        "pl": "Odwiedź profil",
        "es": "Visitar perfil",
        "fr": "Visiter le profil",
        "it": "Visita il profilo",
        "pt": "Visitar perfil",
        "ru": "Посетить профиль",
        "tr": "Profili Ziyaret Et",
    },
    "Account Created": {
        "de": "Konto erstellt am",
        "en": "Account Created on",
        "pl": "Konto utworzone dnia",
        "es": "Cuenta creada el",
        "fr": "Compte créé le",
        "it": "Account creato il",
        "pt": "Conta criada em",
        "ru": "Аккаунт создан",
        "tr": "Hesap Oluşturuldu",
    },
    "Last Updated": {
        "de": "Zuletzt aktualisiert am",
        "en": "Last Updated on",
        "pl": "Ostatnia aktualizacja dnia",
        "es": "Última actualización el",
        "fr": "Dernière mise à jour le",
        "it": "Ultimo aggiornamento il",
        "pt": "Última atualização em",
        "ru": "Последнее обновление",
        "tr": "Son Güncelleme",
    },
    "New Employee": {
        "de": "Neuer Mitarbeiter",
        "en": "New Employee",
        "pl": "Nowy pracownik",
        "es": "Nuevo empleado",
        "fr": "Nouvel employé",
        "it": "Nuovo dipendente",
        "pt": "Novo funcionário",
        "ru": "Новый сотрудник",
        "tr": "Yeni Çalışan",
    },
    "New Assignment": {
        "de": "Neue Zuweisung",
        "en": "New Assignment",
        "pl": "Nowe przypisanie",
        "es": "Nueva asignación",
        "fr": "Nouvelle attribution",
        "it": "Nuova assegnazione",
        "pt": "Nova atribuição",
        "ru": "Новое назначение",
        "tr": "Yeni Atama",
    },
    "No Permission": {
        "de": "Keine Berechtigung",
        "en": "No Permission",
        "pl": "Brak uprawnień",
        "es": "Sin permiso",
        "fr": "Aucune autorisation",
        "it": "Nessuna autorizzazione",
        "pt": "Sem permissão",
        "ru": "Нет доступа",
        "tr": "Yetki Yok",
    },
    "Viewer no permission message": {
        "de": "Du bist nur Viewer. Bitte melde dich mit einem Konto an, das die Rolle User oder Admin hat.",
        "en": "You are only a viewer. Please log in with an account that has the User or Admin role.",
        "pl": "Masz tylko rolę Viewer. Zaloguj się na konto z rolą User lub Admin.",
        "es": "Solo eres visor. Inicia sesión con una cuenta que tenga el rol User o Admin.",
        "fr": "Vous êtes uniquement observateur. Connectez-vous avec un compte ayant le rôle User ou Admin.",
        "it": "Sei solo un visualizzatore. Accedi con un account che abbia il ruolo User o Admin.",
        "pt": "Você é apenas visualizador. Faça login com uma conta que tenha a função User ou Admin.",
        "ru": "У вас роль Viewer. Войдите под учётной записью с ролью User или Admin.",
        "tr": "Yalnızca görüntüleyicisiniz. Lütfen User veya Admin rolüne sahip bir hesapla giriş yapın.",
    },
    "Close": {
        "de": "Schließen",
        "en": "Close",
        "pl": "Zamknij",
        "es": "Cerrar",
        "fr": "Fermer",
        "it": "Chiudi",
        "pt": "Fechar",
        "ru": "Закрыть",
        "tr": "Kapat",
    }
}