export const translatedInfo: Record<string, Record<string, string>> = {
    "Language": {
        "de": "Deutsch",
        "en": "English",
        "pl": "Polski",
        "es": "Español",
        "fr": "Français",
        "it": "Italiano",
        "pt": "Português",
        "ru": "Русский",
        "tr": "Türkçe",
    },
    "EC Inventory Hub 2026 by R.Stolz": {
        "de": "EC Inventory Hub © 2026 von R.Stolz",
        "en": "EC Inventory Hub © 2026 by R.Stolz",
        "pl": "EC Inventory Hub © 2026 przez R.Stolz",
        "es": "EC Inventory Hub © 2026 por R.Stolz",
        "fr": "EC Inventory Hub © 2026 par R.Stolz",
        "it": "EC Inventory Hub © 2026 da R.Stolz",
        "pt": "EC Inventory Hub © 2026 por R.Stolz",
        "ru": "EC Inventory Hub © 2026 от R.Stolz",
        "tr": "EC Inventory Hub © 2026 tarafından R.Stolz",
    },
    "Profile GitHub": {
        "de": "GitHub Profil",
        "en": "GitHub Profile",
        "pl": "Profil GitHub",
        "es": "Perfil de GitHub",
        "fr": "Profil GitHub",
        "it": "Profilo GitHub",
        "pt": "Perfil do GitHub",
        "ru": "Профиль GitHub",
        "tr": "GitHub Profili",
    },
    "Username": {
        "de": "Benutzername",
        "en": "Username",
        "pl": "Nazwa użytkownika",
        "es": "Nombre de usuario",
        "fr": "Nom d'utilisateur",
        "it": "Nome utente",
        "pt": "Nome de usuário",
        "ru": "Имя пользователя",
        "tr": "Kullanıcı adı",
    },
    "Name": {
        "de": "Name",
        "en": "Name",
        "pl": "Imię",
        "es": "Nombre",
        "fr": "Nom",
        "it": "Nome",
        "pt": "Nome",
        "ru": "Имя",
        "tr": "İsim",
    },
    "Location": {
        "de": "Ort",
        "en": "Location",
        "pl": "Lokalizacja",
        "es": "Ubicación",
        "fr": "Emplacement",
        "it": "Posizione",
        "pt": "Localização",
        "ru": "Местоположение",
        "tr": "Konum",
    },
    "Followers": {
        "de": "Follower",
        "en": "Followers",
        "pl": "Obserwujący",
        "es": "Seguidores",
        "fr": "Abonnés",
        "it": "Follower",
        "pt": "Seguidores",
        "ru": "Подписчики",
        "tr": "Takipçiler",
    },
    "Following": {
        "de": "Folgt",
        "en": "Following",
        "pl": "Obserwuje",
        "es": "Siguiendo",
        "fr": "Abonnements",
        "it": "Seguiti",
        "pt": "Seguindo",
        "ru": "Подписки",
        "tr": "Takip Edilenler",
    },
    "Public Repositories": {
        "de": "Öffentliche Repositories",
        "en": "Public Repositories",
        "pl": "Publiczne repozytoria",
        "es": "Repositorios públicos",
        "fr": "Dépôts publics",
        "it": "Repository pubblici",
        "pt": "Repositórios públicos",
        "ru": "Публичные репозитории",
        "tr": "Halka Açık Depolar",
    },
    "Visit Profile": {
        "de": "Profil besuchen",
        "en": "Visit Profile",
        "pl": "Odwiedź profil",
        "es": "Visitar perfil",
        "fr": "Visiter le profil",
        "it": "Visita il profilo",
        "pt": "Visitar perfil",
        "ru": "Посетить профиль",
        "tr": "Profili Ziyaret Et",
    },
    "Account Created": {
        "de": "Konto erstellt am",
        "en": "Account Created on",
        "pl": "Konto utworzone dnia",
        "es": "Cuenta creada el",
        "fr": "Compte créé le",
        "it": "Account creato il",
        "pt": "Conta criada em",
        "ru": "Аккаунт создан",
        "tr": "Hesap Oluşturuldu",
    },
    "Last Updated": {
        "de": "Zuletzt aktualisiert am",
        "en": "Last Updated on",
        "pl": "Ostatnia aktualizacja dnia",
        "es": "Última actualización el",
        "fr": "Dernière mise à jour le",
        "it": "Ultimo aggiornamento il",
        "pt": "Última atualização em",
        "ru": "Последнее обновление",
        "tr": "Son Güncelleme",
    },
    "New Employee": {
        "de": "Neuer Mitarbeiter",
        "en": "New Employee",
        "pl": "Nowy pracownik",
        "es": "Nuevo empleado",
        "fr": "Nouvel employé",
        "it": "Nuovo dipendente",
        "pt": "Novo funcionário",
        "ru": "Новый сотрудник",
        "tr": "Yeni Çalışan",
    },
    "New Location": {
        "de": "Neuer Standort",
        "en": "New Location",
        "pl": "Nowa lokalizacja",
        "es": "Nueva ubicación",
        "fr": "Nouveau site",
        "it": "Nuova sede",
        "pt": "Nova localização",
        "ru": "Новая локация",
        "tr": "Yeni Konum",
    },
    "New Device": {
        "de": "Neues Gerät",
        "en": "New Device",
        "pl": "Nowe urządzenie",
        "es": "Nuevo dispositivo",
        "fr": "Nouvel appareil",
        "it": "Nuovo dispositivo",
        "pt": "Novo dispositivo",
        "ru": "Новое устройство",
        "tr": "Yeni Cihaz",
    },
    "New Assignment": {
        "de": "Neue Zuweisung",
        "en": "New Assignment",
        "pl": "Nowe przypisanie",
        "es": "Nueva asignación",
        "fr": "Nouvelle attribution",
        "it": "Nuova assegnazione",
        "pt": "Nova atribuição",
        "ru": "Новое назначение",
        "tr": "Yeni Atama",
    },
    "No Permission": {
        "de": "Keine Berechtigung",
        "en": "No Permission",
        "pl": "Brak uprawnień",
        "es": "Sin permiso",
        "fr": "Aucune autorisation",
        "it": "Nessuna autorizzazione",
        "pt": "Sem permissão",
        "ru": "Нет доступа",
        "tr": "Yetki Yok",
    },
    "Viewer no permission message": {
        "de": "Du bist nur Viewer. Bitte melde dich mit einem Konto an, das die Rolle User oder Admin hat.",
        "en": "You are only a viewer. Please log in with an account that has the User or Admin role.",
        "pl": "Masz tylko rolę Viewer. Zaloguj się na konto z rolą User lub Admin.",
        "es": "Solo eres visor. Inicia sesión con una cuenta que tenga el rol User o Admin.",
        "fr": "Vous êtes uniquement observateur. Connectez-vous avec un compte ayant le rôle User ou Admin.",
        "it": "Sei solo un visualizzatore. Accedi con un account che abbia il ruolo User o Admin.",
        "pt": "Você é apenas visualizador. Faça login com uma conta que tenha a função User ou Admin.",
        "ru": "У вас роль Viewer. Войдите под учётной записью с ролью User или Admin.",
        "tr": "Yalnızca görüntüleyicisiniz. Lütfen User veya Admin rolüne sahip bir hesapla giriş yapın.",
    },
    "Close": {
        "de": "Schließen",
        "en": "Close",
        "pl": "Zamknij",
        "es": "Cerrar",
        "fr": "Fermer",
        "it": "Chiudi",
        "pt": "Fechar",
        "ru": "Закрыть",
        "tr": "Kapat",
    },
    "Search": {
        "de": "Suchen",
        "en": "Search",
        "pl": "Szukaj",
        "es": "Buscar",
        "fr": "Rechercher",
        "it": "Cerca",
        "pt": "Pesquisar",
        "ru": "Поиск",
        "tr": "Ara",
    },
    "Search for a place...": {
        "de": "Ort suchen...",
        "en": "Search for a place...",
        "pl": "Szukaj miejsca...",
        "es": "Buscar un lugar...",
        "fr": "Rechercher un lieu...",
        "it": "Cerca un luogo...",
        "pt": "Pesquisar um local...",
        "ru": "Найти место...",
        "tr": "Bir yer ara...",
    },
    "Address": {
        "de": "Adresse",
        "en": "Address",
        "pl": "Adres",
        "es": "Dirección",
        "fr": "Adresse",
        "it": "Indirizzo",
        "pt": "Endereço",
        "ru": "Адрес",
        "tr": "Adres",
    },
    "Devices": {
        "de": "Geräte",
        "en": "Devices",
        "pl": "Urządzenia",
        "es": "Dispositivos",
        "fr": "Appareils",
        "it": "Dispositivi",
        "pt": "Dispositivos",
        "ru": "Устройства",
        "tr": "Cihazlar",
    },
    "In repair": {
        "de": "In Reparatur",
        "en": "In repair",
        "pl": "W naprawie",
        "es": "En reparación",
        "fr": "En réparation",
        "it": "In riparazione",
        "pt": "Em reparo",
        "ru": "В ремонте",
        "tr": "Tamirde",
    },
    "Defective": {
        "de": "Defekt",
        "en": "Defective",
        "pl": "Uszkodzone",
        "es": "Defectuoso",
        "fr": "Défectueux",
        "it": "Difettoso",
        "pt": "Defeituoso",
        "ru": "Неисправно",
        "tr": "Arızalı",
    },
    "Role": {
        "de": "Rolle",
        "en": "Role",
        "pl": "Rola",
        "es": "Rol",
        "fr": "Rôle",
        "it": "Ruolo",
        "pt": "Função",
        "ru": "Роль",
        "tr": "Rol",
    },
    "Edit": {
        "de": "Bearbeiten",
        "en": "Edit",
        "pl": "Edytuj",
        "es": "Editar",
        "fr": "Modifier",
        "it": "Modifica",
        "pt": "Editar",
        "ru": "Редактировать",
        "tr": "Düzenle",
    },
    "Delete": {
        "de": "Löschen",
        "en": "Delete",
        "pl": "Usuń",
        "es": "Eliminar",
        "fr": "Supprimer",
        "it": "Elimina",
        "pt": "Excluir",
        "ru": "Удалить",
        "tr": "Sil",
    },
    "Yes, Delete": {
        "de": "Ja, löschen",
        "en": "Yes, Delete",
        "pl": "Tak, usuń",
        "es": "Sí, eliminar",
        "fr": "Oui, supprimer",
        "it": "Sì, elimina",
        "pt": "Sim, excluir",
        "ru": "Да, удалить",
        "tr": "Evet, sil",
    },
    "Cancel": {
        "de": "Abbrechen",
        "en": "Cancel",
        "pl": "Anuluj",
        "es": "Cancelar",
        "fr": "Annuler",
        "it": "Annulla",
        "pt": "Cancelar",
        "ru": "Отмена",
        "tr": "İptal",
    },
    "Delete All": {
        "de": "Alles löschen",
        "en": "Delete All",
        "pl": "Usuń wszystko",
        "es": "Eliminar todo",
        "fr": "Tout supprimer",
        "it": "Elimina tutto",
        "pt": "Excluir tudo",
        "ru": "Удалить всё",
        "tr": "Tümünü sil",
    },
    "Delete Anyway": {
        "de": "Trotzdem löschen",
        "en": "Delete Anyway",
        "pl": "Usuń mimo to",
        "es": "Eliminar de todos modos",
        "fr": "Supprimer quand même",
        "it": "Elimina comunque",
        "pt": "Excluir mesmo assim",
        "ru": "Всё равно удалить",
        "tr": "Yine de sil",
    },
    "remove file": {
        "de": "Datei entfernen",
        "en": "remove file",
        "pl": "usuń plik",
        "es": "eliminar archivo",
        "fr": "supprimer le fichier",
        "it": "rimuovi file",
        "pt": "remover arquivo",
        "ru": "удалить файл",
        "tr": "dosyayı kaldır",
    },
    "remove image": {
        "de": "Bild entfernen",
        "en": "remove image",
        "pl": "usuń obraz",
        "es": "eliminar imagen",
        "fr": "supprimer l'image",
        "it": "rimuovi immagine",
        "pt": "remover imagem",
        "ru": "удалить изображение",
        "tr": "resmi kaldır",
    },
    "back": {
        "de": "zurück",
        "en": "back",
        "pl": "wstecz",
        "es": "atrás",
        "fr": "retour",
        "it": "indietro",
        "pt": "voltar",
        "ru": "назад",
        "tr": "geri",
    },
    "Add Employee": {
        "de": "Mitarbeiter hinzufügen",
        "en": "Add Employee",
        "pl": "Dodaj pracownika",
        "es": "Añadir empleado",
        "fr": "Ajouter un employé",
        "it": "Aggiungi dipendente",
        "pt": "Adicionar funcionário",
        "ru": "Добавить сотрудника",
        "tr": "Çalışan Ekle",
    },
    "Update Employee": {
        "de": "Mitarbeiter aktualisieren",
        "en": "Update Employee",
        "pl": "Zaktualizuj pracownika",
        "es": "Actualizar empleado",
        "fr": "Mettre à jour l'employé",
        "it": "Aggiorna dipendente",
        "pt": "Atualizar funcionário",
        "ru": "Обновить сотрудника",
        "tr": "Çalışanı Güncelle",
    },
    "Add Location": {
        "de": "Standort hinzufügen",
        "en": "Add Location",
        "pl": "Dodaj lokalizację",
        "es": "Añadir ubicación",
        "fr": "Ajouter un site",
        "it": "Aggiungi sede",
        "pt": "Adicionar localização",
        "ru": "Добавить локацию",
        "tr": "Konum Ekle",
    },
    "Update Location": {
        "de": "Standort aktualisieren",
        "en": "Update Location",
        "pl": "Zaktualizuj lokalizację",
        "es": "Actualizar ubicación",
        "fr": "Mettre à jour le site",
        "it": "Aggiorna sede",
        "pt": "Atualizar localização",
        "ru": "Обновить локацию",
        "tr": "Konumu Güncelle",
    },
    "Add Device": {
        "de": "Gerät hinzufügen",
        "en": "Add Device",
        "pl": "Dodaj urządzenie",
        "es": "Añadir dispositivo",
        "fr": "Ajouter un appareil",
        "it": "Aggiungi dispositivo",
        "pt": "Adicionar dispositivo",
        "ru": "Добавить устройство",
        "tr": "Cihaz Ekle",
    },
    "Update Device": {
        "de": "Gerät aktualisieren",
        "en": "Update Device",
        "pl": "Zaktualizuj urządzenie",
        "es": "Actualizar dispositivo",
        "fr": "Mettre à jour l'appareil",
        "it": "Aggiorna dispositivo",
        "pt": "Atualizar dispositivo",
        "ru": "Обновить устройство",
        "tr": "Cihazı Güncelle",
    },
    "Add Assignment": {
        "de": "Zuweisung hinzufügen",
        "en": "Add Assignment",
        "pl": "Dodaj przypisanie",
        "es": "Añadir asignación",
        "fr": "Ajouter une attribution",
        "it": "Aggiungi assegnazione",
        "pt": "Adicionar atribuição",
        "ru": "Добавить назначение",
        "tr": "Atama Ekle",
    },
    "Update Assignment": {
        "de": "Zuweisung aktualisieren",
        "en": "Update Assignment",
        "pl": "Zaktualizuj przypisanie",
        "es": "Actualizar asignación",
        "fr": "Mettre à jour l'attribution",
        "it": "Aggiorna assegnazione",
        "pt": "Atualizar atribuição",
        "ru": "Обновить назначение",
        "tr": "Atamayı Güncelle",
    },
    "Reset Filters": {
        "de": "Filter zurücksetzen",
        "en": "Reset Filters",
        "pl": "Resetuj filtry",
        "es": "Restablecer filtros",
        "fr": "Réinitialiser les filtres",
        "it": "Reimposta filtri",
        "pt": "Redefinir filtros",
        "ru": "Сбросить фильтры",
        "tr": "Filtreleri Sıfırla",
    },
    "Login GitHub": {
        "de": "Login GitHub",
        "en": "Login GitHub",
        "pl": "Zaloguj przez GitHub",
        "es": "Iniciar sesión con GitHub",
        "fr": "Connexion GitHub",
        "it": "Accedi con GitHub",
        "pt": "Entrar com GitHub",
        "ru": "Войти через GitHub",
        "tr": "GitHub ile Giriş",
    },
    "Logout": {
        "de": "Logout",
        "en": "Logout",
        "pl": "Wyloguj",
        "es": "Cerrar sesión",
        "fr": "Déconnexion",
        "it": "Esci",
        "pt": "Sair",
        "ru": "Выйти",
        "tr": "Çıkış",
    },
    "Home": {
        "de": "Start",
        "en": "Home",
        "pl": "Start",
        "es": "Inicio",
        "fr": "Accueil",
        "it": "Home",
        "pt": "Início",
        "ru": "Главная",
        "tr": "Ana Sayfa",
    },
    "Employees": {
        "de": "Mitarbeiter",
        "en": "Employees",
        "pl": "Pracownicy",
        "es": "Empleados",
        "fr": "Employés",
        "it": "Dipendenti",
        "pt": "Funcionários",
        "ru": "Сотрудники",
        "tr": "Çalışanlar",
    },
    "Assignments": {
        "de": "Zuweisungen",
        "en": "Assignments",
        "pl": "Przypisania",
        "es": "Asignaciones",
        "fr": "Attributions",
        "it": "Assegnazioni",
        "pt": "Atribuições",
        "ru": "Назначения",
        "tr": "Atamalar",
    },
    "Locations": {
        "de": "Standorte",
        "en": "Locations",
        "pl": "Lokalizacje",
        "es": "Ubicaciones",
        "fr": "Sites",
        "it": "Sedi",
        "pt": "Localizações",
        "ru": "Локации",
        "tr": "Konumlar",
    },
    "Profile": {
        "de": "Profil",
        "en": "Profile",
        "pl": "Profil",
        "es": "Perfil",
        "fr": "Profil",
        "it": "Profilo",
        "pt": "Perfil",
        "ru": "Профиль",
        "tr": "Profil",
    }
}