spring.application.name=backend

spring.security.oauth2.client.registration.github.client-id=${OAUTH_GITHUB_ID}
spring.security.oauth2.client.registration.github.client-secret=${OAUTH_GITHUB_SECRET}
spring.security.oauth2.client.registration.github.scope=user:email
app.url=${APP_URL}

CLOUDINARY_URL=${CLOUDINARY_URL}
spring.servlet.multipart.max-file-size=5MB

spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.url=${DATABASE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
# set to true only for debugging
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.format_sql=true